---
title: "Resources"
---

## Making a Website

This website was made with [Quarto](https://quarto.org/). 
Source code and files are available [here](https://github.com/kegrinde/kegrinde.github.io).

I found these two resources particularly helpful in building this site:

- [Creating your personal website using Quarto](https://ucsb-meds.github.io/creating-quarto-websites/) by Sam Csik
- [From Zero to Website in Twenty Minutes with Quarto](https://mine-cetinkaya-rundel.github.io/quarto-world-of-possibilities-jsm24/talks/3-websites/) by Charlotte Wickham

## Grad School

Thinking about grad school? Check out the [slides](https://docs.google.com/presentation/d/1wFTzt58C2ajQDycrpa6lSuetHdyVZG36GfLgTiCqJ1w/edit?usp=sharing) or [recording](https://www.causeweb.org/usproc/eusrc/2020/program/grad-school-panel) from a talk I gave about grad school at [eUSR 2020](https://www.causeweb.org/usproc/eusrc/2020/program).

## Job Market

On the job market? Read the [September newsletter](https://higherlogicdownload.s3.amazonaws.com/AMSTAT/6d11267c-5862-4c31-9f1e-f5a52a11ea5f/UploadedImages/Newsletters/Newsletter_SSGG_2021Sept_final.pdf) from the American Statistical Association's Section on Statistics in Genomics and Genetics (SSGG). I contributed some reflections and tips on applying for jobs at liberal arts colleges, and there is also great advice from others on applying for other types of jobs.

## Stay Tuned...

More resources coming soon!